sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t danielmmartin/docker-react .

script:
  - docker run danielmmartin/docker-react npm run test -- --coverage
  