sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t danielmmartin/docker-react .

script:
  - docker run -e CI=true danielmmartin/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-722781481708"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_acess_key:
    secure: "$AWS_SECRET_KEY"